title:            <b><font size='3.75em'>Inventor<font color='black' size='4.75em'>.</font> Biker<font color='black' size='4.75em'>.</font> Foodie<font color='black' size='4.75em'>.</font> Hacker<font color='black' size='4.75em'>.</font> Wanderlust<font color='black' size='4.75em'>. </font> </font><br><br><font size='2.75em'>you will find my notes on <b>life, travel, photography, <u>infosec</u></b> & almost everything I'd love to share.</font>
description:      <font size='2.75em'>Disclaimer - Views expressed throughout the site are my own, you may expect a mediocre profanity factor on the blog posts.</font>

logo:		logo.png
disqus_shortname: sh4in
share:            true
dropcap:	   true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:   ''   	  

# Owner/author information
owner:
  name:           Shankar Damodaran
  avatar:         shan.jpg
  email:          d.shankarnarayana@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Inventor. Hacker. Foodie. Traveller. Biker.
  # Social networking links used in footer. Update and remove as you like.
  twitter:        sh4nx0r
  facebook:       sh4nx0r
  github:         sh4nx0r
  linkedin:	  shankardamodaran      
  instagram:      shankardamodaran
  # For Google Authorship https://plus.google.com/authorship
  #google_plus:    https://plus.google.com/u/0/102602916593522619858

# Analytics and webmaster tools stuff goes here
#google_analytics:   UA-39365944-7
#google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: "#trending"
    url: /trending
  - title: MyCV
    url: /cv
  - title: Connect
    url: /connect

#  - title: Categories
#    url: /categories
#  - title: About
#    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Dhaka
future:      true
highlighter: rouge
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  #siteurl: 'http://sh4nx0r.github.io/Notepad/'
  #relativeLinks: 'http://sh4nx0r.github.io/Notepad/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Engineering"
              value: engineering
            - name: "Physics"
              value: physics
            - name: "Psychology"
              value: psychology
            - name: "Interesting"
              value: interesting
            - name: "Web-Development"
              value: webdevelopment
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
